# Generated by Django 4.0.1 on 2026-01-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
    ]
